# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('hometown', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('conference', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
